logging:
  level:
    root: INFO
    org:
      springframework:
        # web: DEBUG
        security: DEBUG

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

defauth:
  email: ${ADMIN_EMAIL:"hexlet@example.com"}
  password: ${ADMIN_PASS:"qwerty"}
