spring:
  datasource:
    url: "jdbc:h2:mem:app"
    username: "app"
    password: "password"

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

defauth:
  email: "hexlet@example.com"
  password: "qwerty"