spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

sentry:
  exception-resolver-order: -2147483647

rsa:
  public-key: ${RSA_PUBLIC}
  private-key: ${RSA_PRIVATE}

defauth:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASS}