spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

rsa:
  public-key: classpath:${RSA_PUBLIC_PATH}
  private-key: classpath:${RSA_PRIVATE_PATH}

defauth:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASS}